{ ... }:
{
  services.zapret = {
    enable = true;
    params = [
      "--hostspell=hoSt"
      "--dpi-desync=fake --dpi-desync-ttl=4"
      "--dpi-desync=fake --dpi-desync-fooling=badseq"
      "--dpi-desync=fake --dpi-desync-fooling=md5sig"
      "--dpi-desync=fakedsplit --dpi-desync-ttl=4 --dpi-desync-split-pos=1"
      "--dpi-desync=fakedsplit --dpi-desync-fooling=badseq --dpi-desync-split-pos=1"
      "--dpi-desync=fakedsplit --dpi-desync-fooling=md5sig --dpi-desync-split-pos=1"
      "--dpi-desync=fakeddisorder --dpi-desync-ttl=4 --dpi-desync-split-pos=1"
      "--dpi-desync=fakeddisorder --dpi-desync-fooling=badseq --dpi-desync-split-pos=1"
      "--dpi-desync=fakeddisorder --dpi-desync-fooling=datanoack --dpi-desync-split-pos=1"
      "--dpi-desync=fakeddisorder --dpi-desync-fooling=md5sig --dpi-desync-split-pos=1"
      "--dpi-desync=multisplit --dpi-desync-split-pos=10 --dpi-desync-split-seqovl=1"
      "--dpi-desync=multisplit --dpi-desync-split-pos=10,sniext+1 --dpi-desync-split-seqovl=1"
      "--dpi-desync=multisplit --dpi-desync-split-pos=10,sniext+4 --dpi-desync-split-seqovl=1"
      "--dpi-desync=multisplit --dpi-desync-split-pos=10,midsld --dpi-desync-split-seqovl=1"
      "--dpi-desync=multidisorder --dpi-desync-split-pos=2 --dpi-desync-split-seqovl=1"
      "--dpi-desync=multidisorder --dpi-desync-split-pos=sniext+1 --dpi-desync-split-seqovl=sniext"
      "--dpi-desync=multidisorder --dpi-desync-split-pos=sniext+4 --dpi-desync-split-seqovl=sniext+3"
      "--dpi-desync=multidisorder --dpi-desync-split-pos=midsld --dpi-desync-split-seqovl=midsld-1"
      "--dpi-desync=multidisorder --dpi-desync-split-pos=2,midsld --dpi-desync-split-seqovl=1"
      "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=1"
      "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=2"
      "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=3"
      "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=4"
      "--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=5"
      "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=1 --dpi-desync-split-pos=1"
      "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=1"
      "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=3 --dpi-desync-split-pos=1"
      "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=1"
      "--dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-split-pos=1"
      "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=1 --dpi-desync-split-pos=1"
      "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=2 --dpi-desync-split-pos=1"
      "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=3 --dpi-desync-split-pos=1"
      "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=4 --dpi-desync-split-pos=1"
      "--dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=5 --dpi-desync-split-pos=1"
      "--dpi-desync=syndata"
      "--dpi-desync=syndata,multisplit --dpi-desync-split-pos=1"
      "--dpi-desync=syndata,multidisorder --dpi-desync-split-pos=1"
    ];
  };
}
