{ pkgs, inputs, ... }:
{
  imports = [
    ./apps
    ./gaming
    ./programming
    ./security
    ./terminal
  ];

  home.packages = with pkgs; [
    tor-browser-bundle-bin
    ungoogled-chromium
    inputs.zen-browser.packages.${pkgs.system}.default
    termius
    thunderbird
    telegram-desktop
    unrar
    unzip
    vdhcoapp
    vim
    vlc
    pywalfox-native
    bitwarden-desktop
    btop
    neovim
    obs-studio
    obs-studio-plugins.obs-vkcapture
    wget
    vesktop
    filezilla
    zip
    lshw
    dnsutils
    ticktick
    element-desktop
    wpsoffice
    stable.gimp
    mullvad-vpn
    wireguard-tools
    qbittorrent
    stable.android-studio
    realvnc-vnc-viewer
    jdk23
    flameshot
    protonvpn-gui
    protonvpn-cli
    windsurf
    go
    wireshark
    remmina
    kdePackages.kdenlive
    flatpak
    helvum
    qjackctl
    quickemu
    file-roller
  ];
}
