name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        enable_kvm: true
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"